FROM python:3.7-alpine

COPY requirements.txt .

RUN apk add --update --no-cache --virtual .build-deps \
        g++ \
        python3-dev \
        libxml2 \
        libxml2-dev && \
    apk add libxslt-dev && \
    apk add build-base openssl-dev pkgconfig libffi-dev \
    cups-dev jpeg-dev


RUN pip install --no-cache-dir -r requirements.txt 

RUN apk del .build-deps

RUN reset

COPY ./src .
COPY ./test .

RUN mkdir /var/data

ENTRYPOINT ["python", "main.py"]
